# Generated by Django 4.2.3 on 2023-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_alter_menuitem_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="carts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("title_quantity", models.JSONField()),
            ],
        ),
    ]
