# Generated by Django 4.2.5 on 2023-09-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="delivery_cres",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orders",
            name="order_status",
            field=models.SmallIntegerField(default=0),
        ),
    ]
