# Generated by Django 4.2.5 on 2023-09-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0005_orders_delivery_cres_orders_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders", old_name="delivery_cres", new_name="delivery_crews",
        ),
    ]
