# Generated by Django 4.2.5 on 2023-09-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0006_rename_delivery_cres_orders_delivery_crews"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders", old_name="delivery_crews", new_name="delivery_crew",
        ),
    ]
